run:
  timeout: 5m
  tests: true
  build-tags:
    - wireinject

linters-settings:
  cyclop:
    max-complexity: 7
    skip-tests: true

  gocyclo:
    min-complexity: 7

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 3

  goimports:
    local-prefixes: github.com/ocrosby/go-logging

  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 4

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - cyclop
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - cyclop
        - gocyclo

    - path: pkg/logging/fluent\.go
      linters:
        - dupl

    - path: examples/
      linters:
        - errcheck

    - path: wire_gen\.go
      linters:
        - all

    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
