// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/logging/redactor.go
//
// Generated by this command:
//
//	mockgen -source=pkg/logging/redactor.go -destination=pkg/logging/mocks/mock_redactor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	logging "github.com/ocrosby/go-logging/pkg/logging"
	gomock "go.uber.org/mock/gomock"
)

// MockRedactor is a mock of Redactor interface.
type MockRedactor struct {
	ctrl     *gomock.Controller
	recorder *MockRedactorMockRecorder
	isgomock struct{}
}

// MockRedactorMockRecorder is the mock recorder for MockRedactor.
type MockRedactorMockRecorder struct {
	mock *MockRedactor
}

// NewMockRedactor creates a new mock instance.
func NewMockRedactor(ctrl *gomock.Controller) *MockRedactor {
	mock := &MockRedactor{ctrl: ctrl}
	mock.recorder = &MockRedactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedactor) EXPECT() *MockRedactorMockRecorder {
	return m.recorder
}

// Redact mocks base method.
func (m *MockRedactor) Redact(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redact", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Redact indicates an expected call of Redact.
func (mr *MockRedactorMockRecorder) Redact(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redact", reflect.TypeOf((*MockRedactor)(nil).Redact), input)
}

// MockRedactorChainInterface is a mock of RedactorChainInterface interface.
type MockRedactorChainInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRedactorChainInterfaceMockRecorder
	isgomock struct{}
}

// MockRedactorChainInterfaceMockRecorder is the mock recorder for MockRedactorChainInterface.
type MockRedactorChainInterfaceMockRecorder struct {
	mock *MockRedactorChainInterface
}

// NewMockRedactorChainInterface creates a new mock instance.
func NewMockRedactorChainInterface(ctrl *gomock.Controller) *MockRedactorChainInterface {
	mock := &MockRedactorChainInterface{ctrl: ctrl}
	mock.recorder = &MockRedactorChainInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedactorChainInterface) EXPECT() *MockRedactorChainInterfaceMockRecorder {
	return m.recorder
}

// AddRedactor mocks base method.
func (m *MockRedactorChainInterface) AddRedactor(redactor logging.Redactor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRedactor", redactor)
}

// AddRedactor indicates an expected call of AddRedactor.
func (mr *MockRedactorChainInterfaceMockRecorder) AddRedactor(redactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRedactor", reflect.TypeOf((*MockRedactorChainInterface)(nil).AddRedactor), redactor)
}

// Redact mocks base method.
func (m *MockRedactorChainInterface) Redact(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redact", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Redact indicates an expected call of Redact.
func (mr *MockRedactorChainInterfaceMockRecorder) Redact(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redact", reflect.TypeOf((*MockRedactorChainInterface)(nil).Redact), input)
}
