// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ocrosby/go-logging/pkg/logging"
)

// Injectors from wire.go:

func InitializeLogger() logging.Logger {
	config := logging.ProvideConfig()
	redactorChainInterface := logging.ProvideRedactorChain(config)
	logger := logging.ProvideLogger(config, redactorChainInterface)
	return logger
}
